### PR TITLE
python 3 compatibility, and simple tests

### PR DESCRIPTION
**Pull request by tboz203**
I needed a python3 library for java properties, and yours looked the furthest along. I've added a dependency for [six](https://pythonhosted.org/six/) to make the 2/3 compatibility easier, and added a few more tests in. I'm not certain I've got the strings/bytes/unicode bit quite right, but all the tests are passing. Please let me know what you think!

### CODE REVIEW

**Comment by rgbkrk** [comment]
@Tblue what do you think? I'd love to see a python 3 version of this package so we can use it for some ipython/jupyter related work.

**Comment by dmvieira** [comment]
Hey guys, Is it working?

**Comment by rgbkrk** [comment]
This package may need to be forked and shipped under a new name, the maintainer seems busy.

**Comment by dmvieira** [comment]
I tried here, but tests are not passing: https://github.com/globocom/pyjproperties
 Help needed there

**Comment by Tblue** [comment]
Sorry, it took me _way_ too long to merge this! Thank you very much for your work, @tboz203!

**Pull request merged**
